openapi: "3.0.0"
info:
  title: Orders API
  description: API for order management
  version: "1.0.0"
paths:
  /orders:
    get:
      summary: List orders
      responses:
        "200":
          description: List of orders
    post:
      summary: Create order
      responses:
        "201":
          description: Order created
  /orders/{orderId}:
    get:
      summary: Get order by ID
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order details
